# Generated by Django 4.2.16 on 2026-03-27 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('accounts', '0003_customuser_failed_login_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coordinator_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('LECTURER', 'Lecturer'), ('COORDINATOR', 'School Coordinator'), ('ADMIN', 'Admin')], db_index=True, default='STUDENT', max_length=15),
        ),
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinators', to='institutions.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Coordinator Profile',
                'verbose_name_plural': 'School Coordinator Profiles',
            },
        ),
    ]
