# Generated by Django 4.2.16 on 2026-03-14 01:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('letter_grade', models.CharField(choices=[('A', 'A — Excellent (70–100)'), ('B', 'B — Good (60–69)'), ('C', 'C — Average (50–59)'), ('D', 'D — Below Average (45–49)'), ('E', 'E — Pass (40–44)'), ('F', 'F — Fail (0–39)')], max_length=2)),
                ('lecturer_comment', models.TextField(max_length=2000)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(limit_choices_to={'role': 'LECTURER'}, on_delete=django.db.models.deletion.PROTECT, related_name='grades_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_record', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Grade Record',
                'verbose_name_plural': 'Grade Records',
                'ordering': ['-graded_at'],
            },
        ),
    ]
