# Generated by Django 4.2.16 on 2026-03-15 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graderecord',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'LECTURER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
