# Generated by Django 4.2.16 on 2026-03-14 01:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import logbook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(db_index=True)),
                ('work_title', models.CharField(max_length=255)),
                ('activity_description', models.TextField(max_length=5000)),
                ('tools_used', models.TextField(max_length=1000)),
                ('challenges_encountered', models.TextField(blank=True, max_length=2000)),
                ('lessons_learned', models.TextField(blank=True, max_length=2000)),
                ('technical_photo', models.ImageField(blank=True, null=True, upload_to=logbook.models.log_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('internship_month', models.PositiveSmallIntegerField(editable=False)),
                ('internship_week', models.PositiveSmallIntegerField(editable=False)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Log Entry',
                'verbose_name_plural': 'Daily Log Entries',
                'ordering': ['-entry_date'],
                'indexes': [models.Index(fields=['student', 'entry_date'], name='logbook_dai_student_dae0e2_idx'), models.Index(fields=['student', 'internship_month'], name='logbook_dai_student_bc5b8c_idx'), models.Index(fields=['student', 'internship_week'], name='logbook_dai_student_91917c_idx')],
                'unique_together': {('student', 'entry_date')},
            },
        ),
    ]
